/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;
import Student.StudentDatabase;
import Student.StudentUser;
import Admin.AdminRole;
import Gui.HomeFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nour
 */
public class AddStudent extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddStudent.class.getName());

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddStudent = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        departmentBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        genderBox = new javax.swing.JComboBox<>();
        homeButton = new javax.swing.JButton();
        nameError = new javax.swing.JLabel();
        idError = new javax.swing.JLabel();
        ageError = new javax.swing.JLabel();
        departmentError = new javax.swing.JLabel();
        genderError = new javax.swing.JLabel();
        gpa = new javax.swing.JLabel();
        gpaField = new javax.swing.JTextField();
        gpaError = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddStudent.setBackground(new java.awt.Color(151, 219, 255));

        nameLabel.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        nameLabel.setText("Name");

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel4.setText("Department");

        jLabel5.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel5.setText("Gender");

        ageField.setText("Enter student age.");
        ageField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFieldFocusLost(evt);
            }
        });
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        ageField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageFieldKeyReleased(evt);
            }
        });

        nameField.setText("Enter student name.");
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameFieldKeyReleased(evt);
            }
        });

        IDField.setText("Enter student ID.");
        IDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFieldFocusLost(evt);
            }
        });
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });
        IDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IDFieldKeyReleased(evt);
            }
        });

        departmentBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Computer and Communication", "Mechatronics", "Electromechanics", "Biomedical", "Petrochemical", "Civil and Architecture" }));
        departmentBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentBoxActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Salma old\\Downloads\\incorporation.png")); // NOI18N
        addButton.setText("ADD");
        addButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        genderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderBoxActionPerformed(evt);
            }
        });

        homeButton.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        homeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Salma old\\Downloads\\home-button.png")); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        nameError.setBackground(new java.awt.Color(255, 51, 0));
        nameError.setForeground(new java.awt.Color(255, 51, 51));

        idError.setForeground(new java.awt.Color(255, 0, 0));

        ageError.setForeground(new java.awt.Color(255, 51, 0));

        departmentError.setForeground(new java.awt.Color(255, 51, 0));

        genderError.setForeground(new java.awt.Color(255, 51, 0));

        gpa.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        gpa.setText("GPA");

        gpaField.setText("Enter student gpa.");
        gpaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gpaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gpaFieldFocusLost(evt);
            }
        });
        gpaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaFieldActionPerformed(evt);
            }
        });
        gpaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gpaFieldKeyReleased(evt);
            }
        });

        gpaError.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout AddStudentLayout = new javax.swing.GroupLayout(AddStudent);
        AddStudent.setLayout(AddStudentLayout);
        AddStudentLayout.setHorizontalGroup(
            AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddStudentLayout.createSequentialGroup()
                        .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(ageError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ageField))
                            .addGroup(AddStudentLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(nameError, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idError, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddStudentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(AddStudentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddStudentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddStudentLayout.createSequentialGroup()
                        .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddStudentLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departmentError, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departmentBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AddStudentLayout.createSequentialGroup()
                                .addComponent(gpa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gpaError, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gpaField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(AddStudentLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(genderError, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddStudentLayout.setVerticalGroup(
            AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addComponent(nameError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idError, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageError)
                .addGap(41, 41, 41)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddStudentLayout.createSequentialGroup()
                        .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departmentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderError, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(departmentError, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpaError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(194, 194, 194))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private boolean isResetting = false;
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
       this.setVisible(false);
     HomeFrame h=new HomeFrame();
     h.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void genderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderBoxActionPerformed
        if(isResetting) return;
        String temp=genderBox.getSelectedItem().toString();
        if(temp.equals("Select"))
        genderError.setText("Please select a gender.");
        else genderError.setText("");
    }//GEN-LAST:event_genderBoxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
           AdminRole a=new AdminRole();
        String name=nameField.getText();
           String id=IDField.getText();
           String age=ageField.getText();
            String department=departmentBox.getSelectedItem().toString();
            String gender=genderBox.getSelectedItem().toString();
            String gpa=gpaField.getText();
        if(!nameError.getText().isEmpty()||!idError.getText().isEmpty()||!ageError.getText().isEmpty()||!departmentError.getText().isEmpty()||!genderError.getText().isEmpty()||!gpaError.getText().isEmpty())
        {JOptionPane.showMessageDialog(this,"Please check the error messges and try again."); return; }
  
            else if(name.isEmpty()|| name.equals("Enter student name.") ||id.isEmpty()|| age.isEmpty()|| department.trim().equals("Select")|| gender.trim().equals("Select")||gpa.isEmpty())
            {JOptionPane.showMessageDialog(this, "Please type in the empty fields."); return;}
            else       
            {if(a.addStudent(Integer.parseInt(id),name,Integer.parseInt(age),department,gender,Float.parseFloat(gpa)))
            {JOptionPane.showMessageDialog(this, "Student added successfully!");
              nameField.setText("Enter student name.");
           IDField.setText("Enter student ID.");
           ageField.setText("Enter student age.");
           isResetting = true;
             departmentBox.setSelectedItem("Select");
            genderBox.setSelectedItem("Select");
             isResetting = false;
          gpaField.setText("Enter student gpa.");}
            else JOptionPane.showMessageDialog(this, "Unexpected error.");}
     
       
    }//GEN-LAST:event_addButtonActionPerformed

    private void departmentBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentBoxActionPerformed
       if(isResetting) return;
        String temp=departmentBox.getSelectedItem().toString();
        if(temp.equals("Select"))
        departmentError.setText("Please select a department.");
        else departmentError.setText("");
    }//GEN-LAST:event_departmentBoxActionPerformed

    private void IDFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDFieldKeyReleased
        String temp=IDField.getText().trim();
        StudentDatabase s=new StudentDatabase("Students.txt");
        s.readFromFile();
    
        if(temp.isEmpty()) {idError.setText("Required Field."); return;}
        for(int i=0;i<temp.length();i++)
        {if(!Character.isDigit(temp.charAt(i)))
        {idError.setText("age should contain postive whole numbers only."); return;}}
        if(temp.length()<2)
        {idError.setText("ID should be at least 2 characters."); return;}
        if(temp.length()>10)
        {idError.setText("ID can not be longer than 10 characters."); return;}
        int id=Integer.parseInt(temp);
         if(s.containsId(id))
        idError.setText("This ID is already used.");
        else  idError.setText("");
    }//GEN-LAST:event_IDFieldKeyReleased

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    private void IDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusLost
        if(IDField.getText().isEmpty())
        IDField.setText("Enter student ID.");
    }//GEN-LAST:event_IDFieldFocusLost

    private void IDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusGained
        if(IDField.getText().equals("Enter student ID."))
        IDField.setText("");
    }//GEN-LAST:event_IDFieldFocusGained

    private void nameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyReleased
        String name=nameField.getText().trim();
        if(name.isEmpty()) {nameError.setText("Required Field."); return;}
        for (int i = 0; i < name.length(); i++) 
            {  if (!Character.isLetter(name.charAt(i)) && name.charAt(i) != ' ')
            {nameError.setText("Name should only contain letters."); return;}
                }
        
        if(name.length()<2)
        {nameError.setText("Name should be at least 2 characters."); return;}
         if(name.length()>100)
        {nameError.setText("Name can not be longer than 100 characters."); return;}
          nameError.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldKeyReleased

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        if(nameField.getText().isEmpty())
        nameField.setText("Enter student name.");
    }//GEN-LAST:event_nameFieldFocusLost

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        if(nameField.getText().equals("Enter student name."))
        nameField.setText("");
    }//GEN-LAST:event_nameFieldFocusGained

    private void ageFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageFieldKeyReleased
        String temp=ageField.getText().trim();
        if(temp.isEmpty()) {ageError.setText("Required Field."); return;}
        for(int i=0;i<temp.length();i++)
        {if(!Character.isDigit(temp.charAt(i)))
        {ageError.setText("age should contain postive numbers only."); return;}}
        int age =Integer.parseInt(temp);
        if(age<15 || age>100)
        ageError.setText("Invalid age range.");
        else ageError.setText("");
    }//GEN-LAST:event_ageFieldKeyReleased

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void ageFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusLost
        if(ageField.getText().isEmpty())
        ageField.setText("Enter student age.");
    }//GEN-LAST:event_ageFieldFocusLost

    private void ageFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusGained
        if(ageField.getText().equals("Enter student age."))
        ageField.setText("");
    }//GEN-LAST:event_ageFieldFocusGained

    private void gpaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaFieldActionPerformed

    private void gpaFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gpaFieldKeyReleased
        String temp=gpaField.getText().trim();
        if(temp.isEmpty()) {gpaError.setText("Required field."); return;}
        boolean flag=false;
 for(int i=0;i<temp.length();i++)
        {  if(temp.charAt(i)=='.'&&!flag) flag=true;
        else if(temp.charAt(i)=='.'&&flag) 
        {gpaError.setText("Invalid GPA form."); return;}
          else if(!Character.isDigit(temp.charAt(i))) 
        {gpaError.setText("GPA should have numbers only."); return; }
 
        }
        float gpa =Float.parseFloat(temp);
        if(gpa<0 || gpa>4)
        gpaError.setText("Invalid GPA range.");
        else gpaError.setText("");
    }//GEN-LAST:event_gpaFieldKeyReleased

    private void gpaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gpaFieldFocusGained
     if(gpaField.getText().equals("Enter student gpa."))
        gpaField.setText("");
    }//GEN-LAST:event_gpaFieldFocusGained

    private void gpaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gpaFieldFocusLost
        if(gpaField.getText().isEmpty())
        gpaField.setText("Enter student gpa.");
    }//GEN-LAST:event_gpaFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
      
        java.awt.EventQueue.invokeLater(() -> new AddStudent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddStudent;
    private javax.swing.JTextField IDField;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel ageError;
    private javax.swing.JTextField ageField;
    private javax.swing.JComboBox<String> departmentBox;
    private javax.swing.JLabel departmentError;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JLabel genderError;
    private javax.swing.JLabel gpa;
    private javax.swing.JLabel gpaError;
    private javax.swing.JTextField gpaField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel idError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nameError;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
