/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Admin.AdminUser;
import Admin.UserDatabase;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Mariam Yamen
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        createDefaultAdminFile();
    }

    /**
     * Create default admin file with COMMA format (not space)
     */
    private void createDefaultAdminFile() {
        File adminFile = new File("Admin.txt");
        if (!adminFile.exists()) {
            try {
                FileWriter writer = new FileWriter(adminFile);
                writer.write("admin,admin123\n");
                writer.write("user,password\n");
                writer.close();
                logger.info("Default admin file created successfully with comma format");
            } catch (IOException e) {
                logger.severe("Error creating admin file: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtuser = new javax.swing.JTextField();
        blogin = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        jcshow_password = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System - Login");
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Login Information");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username: ");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password:");

        jtuser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuserActionPerformed(evt);
            }
        });

        blogin.setBackground(new java.awt.Color(70, 130, 255));
        blogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        blogin.setForeground(new java.awt.Color(255, 255, 255));
        blogin.setText("Login");
        blogin.setBorder(javax.swing.BorderFactory
                .createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), null));
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });

        bexit.setBackground(new java.awt.Color(255, 100, 100));
        bexit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bexit.setForeground(new java.awt.Color(255, 255, 255));
        bexit.setText("Exit");
        bexit.setBorder(javax.swing.BorderFactory
                .createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), null));
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        jpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });

        jcshow_password.setText("Show Password");
        jcshow_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcshow_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jcshow_password)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(bexit,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                80,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                65, Short.MAX_VALUE)
                                                                                        .addComponent(blogin,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                80,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jtuser)
                                                                        .addComponent(jpassword))))))
                                .addContainerGap(46, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jtuser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addComponent(jcshow_password)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(blogin)
                                        .addComponent(bexit))
                                .addContainerGap(64, Short.MAX_VALUE)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtuserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtuserActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtuserActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bexitActionPerformed
        System.exit(0);
    }// GEN-LAST:event_bexitActionPerformed

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jpasswordActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bloginActionPerformed
        String username = jtuser.getText().trim();
        String password = new String(jpassword.getPassword()).trim();

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your username", "Input Error",
                    JOptionPane.WARNING_MESSAGE);
            jtuser.requestFocus();
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your password", "Input Error",
                    JOptionPane.WARNING_MESSAGE);
            jpassword.requestFocus();
            return;
        }

        try {
            String filename = "Admin.txt";
            UserDatabase userDB = new UserDatabase(filename);
            userDB.readFromFile();

            // Debug: Check what's in the database
            System.out.println("Total users in database: " + userDB.returnAllRecords().size());
            for (AdminUser user : userDB.returnAllRecords()) {
                System.out.println("User: " + user.getSearchKey() + ", Pass: " + user.getPassword());
            }

            if (!userDB.containsName(username)) {
                JOptionPane.showMessageDialog(this, "Invalid username", "Login Failed", JOptionPane.ERROR_MESSAGE);
                jtuser.selectAll();
                jtuser.requestFocus();
                return;
            }

            // Get the user and check password
            AdminUser user = userDB.getRecord(username);
            if (user != null && user.getPassword().equals(password)) {
                // Successful login
                JOptionPane.showMessageDialog(this, "Login successful! Welcome " + username, "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                // Navigate to HomeFrame
                HomeFrame homeFrame = new HomeFrame();
                homeFrame.setVisible(true);
                this.dispose(); // Close login window
            } else {
                JOptionPane.showMessageDialog(this, "Invalid password", "Login Failed", JOptionPane.ERROR_MESSAGE);
                jpassword.selectAll();
                jpassword.requestFocus();
            }

        } catch (Exception e) {
            logger.severe("Login error: " + e.getMessage());
            e.printStackTrace();

            // Try to fix the admin file with correct format
            fixAdminFile();

            JOptionPane.showMessageDialog(this,
                    "System error detected. Admin file has been reset.\n\n" +
                            "Please try again with:\n" +
                            "Username: admin\n" +
                            "Password: admin123",
                    "System Reset",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }// GEN-LAST:event_bloginActionPerformed

    private void jcshow_passwordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jcshow_passwordActionPerformed
        if (jcshow_password.isSelected()) {
            jpassword.setEchoChar((char) 0); // Show password
        } else {
            jpassword.setEchoChar('*'); // Hide password
        }
    }// GEN-LAST:event_jcshow_passwordActionPerformed

    /**
     * Fix corrupted admin file by recreating it with COMMA format
     */
    private void fixAdminFile() {
        try {
            File adminFile = new File("Admin.txt");
            if (adminFile.exists()) {
                adminFile.delete();
            }
            createDefaultAdminFile();
            logger.info("Admin file has been reset with comma format");
        } catch (Exception e) {
            logger.severe("Error fixing admin file: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.JButton blogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox jcshow_password;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtuser;
    // End of variables declaration//GEN-END:variables
}